#!/usr/bin/env python3
# -*- coding: utf-8 -*-

"""
compare_viewer_vs_parser_v5_corpus_v1_1.py

Corpus-level validator for:

    CLF Viewer Balloon screenshots -> reconstructed CSV
                versus
    CF2 binary -> cf2_parser_v5.py

Purpose
-------
Keep BOTH sources independent and let the corpus determine the coordinate /
frequency correspondence. The script does NOT modify the parser and does NOT
rewrite the reconstructed image data.

For every matched model it searches:

  frequency slot shift : configurable, default -2,-1,0,+1,+2
  arc mapping          : direct y, reversed (36-y)
  azimuth direction    : +x, -x
  azimuth offset       : 0..355 deg in 5 deg steps

The search is performed on a deterministic sample for speed. The best N
hypotheses are then recomputed using all available reconstructed points.

Expected viewer input
---------------------
Wide CSV generated by extract_balloon_spectra_v1.py, typically:

    extracted_balloon_spectra_v1/<MODEL>/<MODEL>__spectra_wide.csv

Expected parser
---------------
cf2_parser_v5.py exposing CF2File.directivity_slot(slot).

Outputs
-------
match_manifest.csv
corpus_summary.csv
corpus_hypotheses_top.csv
corpus_summary.txt

Scientific interpretation
-------------------------
A systematic Viewer<->parser transformation does NOT automatically imply that
the binary parser is wrong. It can represent a Viewer scrollbar convention,
display-grid convention, or frequency-cell display convention. Parser changes
should only be made after corpus-wide evidence distinguishes those cases.
"""

from __future__ import annotations

import argparse
import csv
import hashlib
import importlib.util
import math
import re
import sys
import time
import unicodedata
from collections import Counter, defaultdict
from pathlib import Path

import numpy as np


# Corrected CLF Viewer visible frequency grid.
#
# The 29 vertical plot lines are 40 Hz ... 25 kHz. This was established both
# geometrically from the rendered labels (63, 125, 250, ... 16k) and by the
# corpus panel: the older extractor grid (31.5 ... 20k) required a systematic
# parser shift of +1 slot on every high-quality model.
VIEWER_FREQS = np.array([
    40, 50, 63, 80, 100, 125, 160, 200, 250, 315,
    400, 500, 630, 800, 1000, 1250, 1600, 2000, 2500,
    3150, 4000, 5000, 6300, 8000, 10000, 12500, 16000,
    20000, 25000,
], dtype=float)

N_X = 72
N_Y = 37
N_GLOBAL_FREQ = 30

NODATA_VALUE = -12000.0
NODATA_TOL = 1e-2


def freq_col_name(freq: float) -> str:
    if float(freq).is_integer():
        return f"db_{int(freq)}"
    return "db_" + str(float(freq)).rstrip("0").rstrip(".").replace(".", "_")


def normalize_name(text: str) -> str:
    text = unicodedata.normalize("NFKD", str(text))
    text = "".join(ch for ch in text if not unicodedata.combining(ch))
    return "".join(ch for ch in text.casefold() if ch.isalnum())


def parse_int_list(text: str):
    out = []
    for token in text.split(","):
        token = token.strip()
        if token:
            out.append(int(token))
    if not out:
        raise ValueError("Empty integer list")
    return sorted(set(out))


def load_parser_module(parser_path: Path):
    parser_path = Path(parser_path).resolve()

    module_name = "cf2_parser_candidate"

    spec = importlib.util.spec_from_file_location(
        module_name,
        parser_path,
    )

    if spec is None or spec.loader is None:
        raise RuntimeError(f"Cannot import parser: {parser_path}")

    module = importlib.util.module_from_spec(spec)

    # Needed by dataclasses when dynamically importing a module.
    sys.modules[module_name] = module

    spec.loader.exec_module(module)

    if not hasattr(module, "CF2File"):
        raise AttributeError("Parser does not expose CF2File")

    if not hasattr(module, "CF2_FREQS"):
        raise AttributeError("Parser does not expose CF2_FREQS")

    return module


def first_csv_model(path: Path):
    """
    Read only the first data row to recover the authoritative `model` column.
    """
    try:
        with path.open("r", encoding="utf-8-sig", newline="") as f:
            reader = csv.DictReader(f)
            row = next(reader, None)
            if row and row.get("model"):
                return row["model"].strip()
    except Exception:
        pass

    stem = path.stem
    stem = re.sub(
        r"__spectra_wide.*$",
        "",
        stem,
        flags=re.IGNORECASE,
    )
    return stem


def discover_viewer_csvs(root: Path):
    """
    Return model -> chosen wide CSV.

    If duplicates exist, the largest file is selected automatically. This is
    useful when a small prototype CSV and a full 2664-state CSV coexist.
    """
    root = Path(root)
    grouped = defaultdict(list)

    for p in root.rglob("*.csv"):
        name = p.name.casefold()

        if "spectra_wide" not in name:
            continue

        model = first_csv_model(p)

        if model:
            grouped[model].append(p)

    chosen = {}

    for model, paths in grouped.items():
        paths = sorted(
            paths,
            key=lambda p: (p.stat().st_size, str(p)),
            reverse=True,
        )

        chosen[model] = {
            "path": paths[0],
            "candidates": paths,
        }

    return chosen


def discover_cf2_files(root: Path):
    return sorted(
        p
        for p in Path(root).rglob("*")
        if p.is_file() and p.suffix.casefold() == ".cf2"
    )


def build_cf2_indexes(paths):
    by_exact = defaultdict(list)
    by_norm = defaultdict(list)

    for p in paths:
        by_exact[p.stem.casefold()].append(p)
        by_norm[normalize_name(p.stem)].append(p)

    return by_exact, by_norm


def match_cf2(model: str, by_exact, by_norm):
    exact = by_exact.get(model.casefold(), [])

    if len(exact) == 1:
        return exact[0], "exact"

    if len(exact) > 1:
        return None, "ambiguous_exact"

    norm = by_norm.get(normalize_name(model), [])

    if len(norm) == 1:
        return norm[0], "normalized"

    if len(norm) > 1:
        return None, "ambiguous_normalized"

    return None, "unmatched"


def load_viewer_cube(
    path: Path,
    min_confidence: float = 0.0,
):
    """
    V shape = (29 viewer grid frequencies, 72 x-index, 37 y-index)
    """
    cube = np.full(
        (len(VIEWER_FREQS), N_X, N_Y),
        np.nan,
        dtype=np.float64,
    )

    confidence = np.full(
        (N_X, N_Y),
        np.nan,
        dtype=np.float64,
    )

    rows_read = 0
    bad_rows = 0

    cols = [freq_col_name(f) for f in VIEWER_FREQS]

    with Path(path).open(
        "r",
        encoding="utf-8-sig",
        newline="",
    ) as f:
        reader = csv.DictReader(f)

        for row in reader:
            rows_read += 1

            try:
                x = int(row["x_index"])
                y = int(row["y_index"])
            except Exception:
                bad_rows += 1
                continue

            if not (0 <= x < N_X and 0 <= y < N_Y):
                bad_rows += 1
                continue

            try:
                c = float(row.get("mean_confidence", "nan"))
            except Exception:
                c = float("nan")

            confidence[x, y] = c

            if (
                min_confidence > 0
                and np.isfinite(c)
                and c < min_confidence
            ):
                continue

            for fi, col in enumerate(cols):
                raw = row.get(col, "")

                if raw is None:
                    continue

                raw = str(raw).strip()

                if not raw:
                    continue

                try:
                    value = float(raw)
                except Exception:
                    continue

                if np.isfinite(value):
                    cube[fi, x, y] = value

    return {
        "cube": cube,
        "confidence": confidence,
        "rows_read": rows_read,
        "bad_rows": bad_rows,
        "finite_points": int(np.isfinite(cube).sum()),
    }


def build_parser_cube(cf2):
    """
    Shape: (30 global frequency slots, 72 azimuth, 37 arc)
    """
    return np.stack(
        [
            np.asarray(
                cf2.directivity_slot(slot),
                dtype=np.float64,
            )
            for slot in range(N_GLOBAL_FREQ)
        ],
        axis=0,
    )


def deterministic_sample(coords, n: int, model: str):
    if len(coords) <= n:
        return coords

    seed_bytes = hashlib.sha256(
        model.encode("utf-8")
    ).digest()[:8]

    seed = int.from_bytes(
        seed_bytes,
        "little",
        signed=False,
    )

    rng = np.random.default_rng(seed)

    indexes = rng.choice(
        len(coords),
        size=n,
        replace=False,
    )

    return coords[np.sort(indexes)]


def valid_parser_values(values):
    return (
        np.isfinite(values)
        & (np.abs(values - NODATA_VALUE) > NODATA_TOL)
        & (np.abs(values) < 1000.0)
    )


def viewer_freq_base_slots(parser_freqs):
    """Map CLF Viewer display-grid frequencies to parser global slots.

    Frequencies not present in the parser table (currently 25 kHz) receive
    -999 and are excluded from comparison.
    """
    parser_freqs = np.asarray(parser_freqs, dtype=float)
    slots = []
    for freq in VIEWER_FREQS:
        matches = np.where(np.isclose(parser_freqs, float(freq), atol=1e-6, rtol=0.0))[0]
        slots.append(int(matches[0]) if len(matches) == 1 else -999)
    return np.asarray(slots, dtype=int)


def search_hypotheses(
    viewer_cube,
    parser_cube,
    parser_freqs,
    declared_min_idx,
    declared_max_idx,
    model,
    shifts,
    sample_points,
    declared_only,
    min_points,
):
    """
    Search on a deterministic subset. Azimuth offsets are evaluated in one
    vectorized 72-offset batch for every shift/arc/direction combination.
    """
    coords = np.argwhere(
        np.isfinite(viewer_cube)
    )

    if len(coords) == 0:
        return []

    coords = deterministic_sample(
        coords,
        sample_points,
        model,
    )

    fi = coords[:, 0]
    xi = coords[:, 1]
    yi = coords[:, 2]

    viewer_values = viewer_cube[
        fi,
        xi,
        yi,
    ]

    parser_freqs = np.asarray(
        parser_freqs,
        dtype=float,
    )

    base_slots = viewer_freq_base_slots(
        parser_freqs
    )

    offsets = np.arange(
        N_X,
        dtype=int,
    )[:, None]

    rows = []

    for shift in shifts:
        slots = base_slots[fi] + int(shift)

        slot_ok = (
            (slots >= 0)
            & (slots < N_GLOBAL_FREQ)
        )

        if declared_only:
            slot_ok &= (
                (slots >= int(declared_min_idx))
                & (slots <= int(declared_max_idx))
            )

        for arc_reverse in (False, True):
            arc_idx = (
                (N_Y - 1 - yi)
                if arc_reverse
                else yi
            )

            for az_direction in (1, -1):
                base_az = (
                    int(az_direction) * xi
                ) % N_X

                az_idx = (
                    base_az[None, :]
                    + offsets
                ) % N_X

                slot_idx = np.broadcast_to(
                    slots[None, :],
                    az_idx.shape,
                )

                arc_matrix = np.broadcast_to(
                    arc_idx[None, :],
                    az_idx.shape,
                )

                # Invalid global slots must be temporarily clipped before
                # advanced indexing. slot_ok masks them out immediately after.
                slot_idx_safe = np.clip(
                    slot_idx,
                    0,
                    N_GLOBAL_FREQ - 1,
                )

                pv = parser_cube[
                    slot_idx_safe,
                    az_idx,
                    arc_matrix,
                ]

                valid = (
                    np.broadcast_to(
                        slot_ok[None, :],
                        pv.shape,
                    )
                    & valid_parser_values(pv)
                )

                diff = (
                    viewer_values[None, :]
                    - pv
                )

                abs_diff = np.where(
                    valid,
                    np.abs(diff),
                    0.0,
                )

                sq_diff = np.where(
                    valid,
                    diff * diff,
                    0.0,
                )

                signed_diff = np.where(
                    valid,
                    diff,
                    0.0,
                )

                counts = valid.sum(axis=1)

                sum_abs = abs_diff.sum(axis=1)
                sum_sq = sq_diff.sum(axis=1)
                sum_signed = signed_diff.sum(axis=1)

                with np.errstate(
                    divide="ignore",
                    invalid="ignore",
                ):
                    maes = sum_abs / counts
                    rmses = np.sqrt(
                        sum_sq / counts
                    )
                    biases = (
                        sum_signed / counts
                    )

                for offset_idx in range(N_X):
                    n = int(counts[offset_idx])

                    if n < min_points:
                        continue

                    rows.append({
                        "freq_shift": int(shift),
                        "arc_mode": (
                            "reverse"
                            if arc_reverse
                            else "direct"
                        ),
                        "az_direction": int(
                            az_direction
                        ),
                        "az_offset_index": int(
                            offset_idx
                        ),
                        "az_offset_deg": int(
                            offset_idx * 5
                        ),
                        "search_n": n,
                        "search_mae_db": float(
                            maes[offset_idx]
                        ),
                        "search_rmse_db": float(
                            rmses[offset_idx]
                        ),
                        "search_bias_db": float(
                            biases[offset_idx]
                        ),
                    })

    rows.sort(
        key=lambda r: (
            r["search_mae_db"],
            r["search_rmse_db"],
            abs(r["search_bias_db"]),
            abs(r["freq_shift"]),
            0 if r["arc_mode"] == "direct" else 1,
            0 if r["az_direction"] == 1 else 1,
            r["az_offset_index"],
        )
    )

    return rows


def full_metrics(
    viewer_cube,
    parser_cube,
    parser_freqs,
    declared_min_idx,
    declared_max_idx,
    hypothesis,
    declared_only,
):
    coords = np.argwhere(
        np.isfinite(viewer_cube)
    )

    fi = coords[:, 0]
    xi = coords[:, 1]
    yi = coords[:, 2]

    vv = viewer_cube[
        fi,
        xi,
        yi,
    ]

    parser_freqs = np.asarray(
        parser_freqs,
        dtype=float,
    )

    base_slots = viewer_freq_base_slots(
        parser_freqs
    )

    slots = (
        base_slots[fi]
        + int(
            hypothesis[
                "freq_shift"
            ]
        )
    )

    ok = (
        (slots >= 0)
        & (slots < N_GLOBAL_FREQ)
    )

    if declared_only:
        ok &= (
            (slots >= int(declared_min_idx))
            & (slots <= int(declared_max_idx))
        )

    arc_idx = (
        (N_Y - 1 - yi)
        if hypothesis["arc_mode"] == "reverse"
        else yi
    )

    az_idx = (
        int(
            hypothesis[
                "az_direction"
            ]
        )
        * xi
        + int(
            hypothesis[
                "az_offset_index"
            ]
        )
    ) % N_X

    safe_slots = np.clip(
        slots,
        0,
        N_GLOBAL_FREQ - 1,
    )

    pv = parser_cube[
        safe_slots,
        az_idx,
        arc_idx,
    ]

    ok &= valid_parser_values(
        pv
    )

    if not np.any(ok):
        return {
            "full_n": 0,
            "full_mae_db": float("nan"),
            "full_rmse_db": float("nan"),
            "full_bias_db": float("nan"),
            "full_median_abs_db": float("nan"),
            "full_p90_abs_db": float("nan"),
            "full_p95_abs_db": float("nan"),
            "within_0_25": float("nan"),
            "within_0_50": float("nan"),
            "within_1_00": float("nan"),
        }

    err = (
        vv[ok]
        - pv[ok]
    )

    abs_err = np.abs(
        err
    )

    return {
        "full_n": int(len(err)),
        "full_mae_db": float(
            np.mean(abs_err)
        ),
        "full_rmse_db": float(
            np.sqrt(
                np.mean(
                    err * err
                )
            )
        ),
        "full_bias_db": float(
            np.mean(err)
        ),
        "full_median_abs_db": float(
            np.median(abs_err)
        ),
        "full_p90_abs_db": float(
            np.quantile(
                abs_err,
                0.90,
            )
        ),
        "full_p95_abs_db": float(
            np.quantile(
                abs_err,
                0.95,
            )
        ),
        "within_0_25": float(
            np.mean(
                abs_err <= 0.25
            )
        ),
        "within_0_50": float(
            np.mean(
                abs_err <= 0.50
            )
        ),
        "within_1_00": float(
            np.mean(
                abs_err <= 1.00
            )
        ),
    }


def quality_class(metrics):
    n = metrics["full_n"]
    mae = metrics["full_mae_db"]
    p90 = metrics["full_p90_abs_db"]

    if n <= 0 or not np.isfinite(mae):
        return "NO_COMPARISON"

    if mae <= 0.25 and p90 <= 0.50:
        return "EXCELLENT"

    if mae <= 0.50 and p90 <= 1.00:
        return "GOOD"

    if mae <= 1.00 and p90 <= 2.00:
        return "REVIEW"

    return "POOR"


def process_model(
    model,
    viewer_csv,
    cf2_path,
    parser_module,
    args,
):
    viewer = load_viewer_cube(
        viewer_csv,
        min_confidence=args.min_confidence,
    )

    cf2 = parser_module.CF2File(
        cf2_path
    )

    parser_cube = build_parser_cube(
        cf2
    )

    hypotheses = search_hypotheses(
        viewer_cube=viewer["cube"],
        parser_cube=parser_cube,
        parser_freqs=parser_module.CF2_FREQS,
        declared_min_idx=cf2.declared_min_idx,
        declared_max_idx=cf2.declared_max_idx,
        model=model,
        shifts=args.freq_shifts,
        sample_points=args.sample_points,
        declared_only=args.declared_only,
        min_points=args.min_search_points,
    )

    if not hypotheses:
        raise RuntimeError(
            "No valid comparison hypotheses"
        )

    top_candidates = hypotheses[
        :max(
            args.top_k,
            2,
        )
    ]

    top_full = []

    for rank, h in enumerate(
        top_candidates,
        1,
    ):
        row = dict(h)

        row.update(
            full_metrics(
                viewer_cube=viewer["cube"],
                parser_cube=parser_cube,
                parser_freqs=parser_module.CF2_FREQS,
                declared_min_idx=cf2.declared_min_idx,
                declared_max_idx=cf2.declared_max_idx,
                hypothesis=h,
                declared_only=args.declared_only,
            )
        )

        row[
            "rank"
        ] = rank

        top_full.append(
            row
        )

    # Re-sort using FULL metrics, not sample metrics.
    top_full.sort(
        key=lambda r: (
            r["full_mae_db"],
            r["full_rmse_db"],
            abs(r["full_bias_db"]),
            r["search_mae_db"],
        )
    )

    for rank, row in enumerate(
        top_full,
        1,
    ):
        row["rank"] = rank

    best = top_full[0]

    if len(top_full) > 1:
        second = top_full[1]
    else:
        second = None

    # Ambiguity is measured on the search set because it includes all 72
    # azimuth offsets, not just the top-K full recomputations.
    near_tol = float(
        args.near_best_mae_tol
    )

    best_search_mae = float(
        hypotheses[0][
            "search_mae_db"
        ]
    )

    near = [
        h
        for h in hypotheses
        if (
            h[
                "search_mae_db"
            ]
            <=
            best_search_mae
            +
            near_tol
        )
    ]

    best_transform_family = [
        h
        for h in near
        if (
            h["freq_shift"]
            ==
            best["freq_shift"]
            and
            h["arc_mode"]
            ==
            best["arc_mode"]
        )
    ]

    az_pairs = {
        (
            h["az_direction"],
            h["az_offset_index"],
        )
        for h in best_transform_family
    }

    azimuth_ambiguous = (
        len(az_pairs) > 1
    )

    metadata = cf2.metadata

    declared = cf2.declared_frequencies

    summary = {
        "model": model,
        "viewer_csv": str(viewer_csv),
        "cf2_file": str(cf2_path),
        "cf2_version": int(cf2.version),
        "cf2_size": int(cf2.file_size),
        "metadata_model_name": str(
            metadata.get(
                "model_name",
                "",
            )
        ),
        "balloon_symmetry": str(
            cf2.balloon_symmetry
        ),
        "declared_min_idx": int(
            cf2.declared_min_idx
        ),
        "declared_max_idx": int(
            cf2.declared_max_idx
        ),
        "declared_first_hz": (
            float(declared[0])
            if len(declared)
            else ""
        ),
        "declared_last_hz": (
            float(declared[-1])
            if len(declared)
            else ""
        ),
        "viewer_rows": int(
            viewer["rows_read"]
        ),
        "viewer_finite_points": int(
            viewer["finite_points"]
        ),
        "best_freq_shift": int(
            best["freq_shift"]
        ),
        "best_arc_mode": best[
            "arc_mode"
        ],
        "best_az_direction": int(
            best["az_direction"]
        ),
        "best_az_offset_index": int(
            best["az_offset_index"]
        ),
        "best_az_offset_deg": int(
            best["az_offset_deg"]
        ),
        "best_n": int(
            best["full_n"]
        ),
        "best_mae_db": float(
            best["full_mae_db"]
        ),
        "best_rmse_db": float(
            best["full_rmse_db"]
        ),
        "best_bias_db": float(
            best["full_bias_db"]
        ),
        "best_median_abs_db": float(
            best["full_median_abs_db"]
        ),
        "best_p90_abs_db": float(
            best["full_p90_abs_db"]
        ),
        "best_p95_abs_db": float(
            best["full_p95_abs_db"]
        ),
        "best_within_0_25": float(
            best["within_0_25"]
        ),
        "best_within_0_50": float(
            best["within_0_50"]
        ),
        "best_within_1_00": float(
            best["within_1_00"]
        ),
        "quality": quality_class(
            best
        ),
        "near_best_count": int(
            len(near)
        ),
        "azimuth_candidate_count": int(
            len(az_pairs)
        ),
        "azimuth_ambiguous": bool(
            azimuth_ambiguous
        ),
        "second_mae_db": (
            float(
                second[
                    "full_mae_db"
                ]
            )
            if second
            else ""
        ),
        "delta_second_mae_db": (
            float(
                second[
                    "full_mae_db"
                ]
                -
                best[
                    "full_mae_db"
                ]
            )
            if second
            else ""
        ),
    }

    top_rows = []

    for row in top_full:
        out = {
            "model": model,
            "cf2_file": str(cf2_path),
        }
        out.update(
            row
        )
        top_rows.append(
            out
        )

    return summary, top_rows


def write_csv(path, rows, fieldnames=None):
    path = Path(path)
    path.parent.mkdir(
        parents=True,
        exist_ok=True,
    )

    if not rows:
        path.write_text(
            "",
            encoding="utf-8",
        )
        return

    if fieldnames is None:
        seen = []

        for row in rows:
            for key in row:
                if key not in seen:
                    seen.append(key)

        fieldnames = seen

    with path.open(
        "w",
        encoding="utf-8-sig",
        newline="",
    ) as f:
        writer = csv.DictWriter(
            f,
            fieldnames=fieldnames,
            extrasaction="ignore",
        )

        writer.writeheader()
        writer.writerows(
            rows
        )


def format_transform(row):
    direction = (
        "+x"
        if int(
            row[
                "best_az_direction"
            ]
        ) == 1
        else "-x"
    )

    return (
        f"freq {int(row['best_freq_shift']):+d}; "
        f"arc {row['best_arc_mode']}; "
        f"az {direction} "
        f"+ {int(row['best_az_offset_deg'])}deg"
    )


def main():
    ap = argparse.ArgumentParser()

    ap.add_argument(
        "--parser",
        type=Path,
        required=True,
    )

    ap.add_argument(
        "--cf2-dir",
        type=Path,
        required=True,
    )

    ap.add_argument(
        "--viewer-root",
        type=Path,
        required=True,
    )

    ap.add_argument(
        "--output-dir",
        type=Path,
        required=True,
    )

    ap.add_argument(
        "--models",
        default="",
        help=(
            "Comma-separated viewer model names. "
            "Empty = all discovered models."
        ),
    )

    ap.add_argument(
        "--freq-shifts",
        default="-2,-1,0,1,2",
        help="Parser global-slot shift candidates.",
    )

    ap.add_argument(
        "--sample-points",
        type=int,
        default=3000,
    )

    ap.add_argument(
        "--top-k",
        type=int,
        default=8,
    )

    ap.add_argument(
        "--min-search-points",
        type=int,
        default=100,
    )

    ap.add_argument(
        "--min-confidence",
        type=float,
        default=0.0,
    )

    ap.add_argument(
        "--declared-only",
        action="store_true",
        help=(
            "Restrict parser values to header-declared frequency slots. "
            "Default search uses all raw global slots for reverse engineering."
        ),
    )

    ap.add_argument(
        "--near-best-mae-tol",
        type=float,
        default=0.01,
        help=(
            "Hypotheses within this sampled MAE of the best are treated "
            "as equivalent/ambiguous."
        ),
    )

    ap.add_argument(
        "--consensus-max-mae",
        type=float,
        default=1.00,
        help=(
            "Optional broad guardrail for structural-consensus candidates. "
            "Robust median/P90 limits below are the primary criteria."
        ),
    )

    ap.add_argument(
        "--consensus-max-median",
        type=float,
        default=0.25,
        help="Maximum median absolute error for mapping consensus.",
    )

    ap.add_argument(
        "--consensus-max-p90",
        type=float,
        default=0.50,
        help="Maximum P90 absolute error for mapping consensus.",
    )

    args = ap.parse_args()

    args.freq_shifts = parse_int_list(
        args.freq_shifts
    )

    args.output_dir.mkdir(
        parents=True,
        exist_ok=True,
    )

    parser_module = load_parser_module(
        args.parser
    )

    viewer = discover_viewer_csvs(
        args.viewer_root
    )

    cf2_paths = discover_cf2_files(
        args.cf2_dir
    )

    by_exact, by_norm = build_cf2_indexes(
        cf2_paths
    )

    if args.models.strip():
        requested = {
            x.strip()
            for x in args.models.split(",")
            if x.strip()
        }

        model_names = [
            m
            for m in sorted(viewer)
            if m in requested
        ]
    else:
        model_names = sorted(
            viewer
        )

    manifest = []
    jobs = []

    for model in model_names:
        viewer_path = viewer[model]["path"]
        duplicates = viewer[model]["candidates"]

        cf2_path, method = match_cf2(
            model,
            by_exact,
            by_norm,
        )

        row = {
            "model": model,
            "viewer_csv": str(
                viewer_path
            ),
            "viewer_csv_candidates": len(
                duplicates
            ),
            "match_method": method,
            "cf2_file": (
                str(cf2_path)
                if cf2_path
                else ""
            ),
        }

        if cf2_path is None:
            row["status"] = "NO_MATCH"
        else:
            row["status"] = "MATCHED"
            jobs.append(
                (
                    model,
                    viewer_path,
                    cf2_path,
                )
            )

        manifest.append(
            row
        )

    summary_rows = []
    top_rows = []
    errors = []

    start_all = time.time()

    print(
        "=" * 80
    )
    print(
        "VIEWER CSV vs CF2 PARSER CORPUS VALIDATION"
    )
    print(
        "=" * 80
    )
    print(
        f"Viewer models discovered : {len(viewer)}"
    )
    print(
        f"CF2 files discovered     : {len(cf2_paths)}"
    )
    print(
        f"Models selected          : {len(model_names)}"
    )
    print(
        f"Matched jobs             : {len(jobs)}"
    )
    print(
        f"Frequency shifts         : {args.freq_shifts}"
    )
    print(
        f"Search sample/model      : {args.sample_points}"
    )
    print()

    for index, (
        model,
        viewer_csv,
        cf2_path,
    ) in enumerate(
        jobs,
        1,
    ):
        t0 = time.time()

        try:
            summary, top = process_model(
                model=model,
                viewer_csv=viewer_csv,
                cf2_path=cf2_path,
                parser_module=parser_module,
                args=args,
            )

            summary_rows.append(
                summary
            )

            top_rows.extend(
                top
            )

            dt = time.time() - t0

            print(
                f"[{index:4d}/{len(jobs)}] "
                f"{model}: "
                f"{summary['quality']} | "
                f"MAE={summary['best_mae_db']:.4f} dB | "
                f"{format_transform(summary)} | "
                f"ambig_az={summary['azimuth_ambiguous']} | "
                f"{dt:.2f}s"
            )

        except Exception as exc:
            errors.append({
                "model": model,
                "viewer_csv": str(
                    viewer_csv
                ),
                "cf2_file": str(
                    cf2_path
                ),
                "error": (
                    f"{type(exc).__name__}: {exc}"
                ),
            })

            print(
                f"[{index:4d}/{len(jobs)}] "
                f"{model}: ERROR "
                f"{type(exc).__name__}: {exc}"
            )

    write_csv(
        args.output_dir
        /
        "match_manifest.csv",
        manifest,
    )

    write_csv(
        args.output_dir
        /
        "corpus_summary.csv",
        summary_rows,
    )

    write_csv(
        args.output_dir
        /
        "corpus_hypotheses_top.csv",
        top_rows,
    )

    write_csv(
        args.output_dir
        /
        "errors.csv",
        errors,
    )

    qualities = Counter(
        row["quality"]
        for row in summary_rows
    )

    # Mapping consensus uses ROBUST error statistics. A small number of
    # raster-tracing outliers can inflate MAE/RMSE while the coordinate mapping
    # is still unambiguous.
    good_for_consensus = [
        row
        for row in summary_rows
        if (
            float(row["best_mae_db"]) <= args.consensus_max_mae
            and float(row["best_median_abs_db"]) <= args.consensus_max_median
            and float(row["best_p90_abs_db"]) <= args.consensus_max_p90
        )
    ]

    freq_consensus = Counter(
        int(
            row[
                "best_freq_shift"
            ]
        )
        for row in good_for_consensus
    )

    arc_consensus = Counter(
        row[
            "best_arc_mode"
        ]
        for row in good_for_consensus
    )

    # Azimuth consensus only from models where the search was not ambiguous.
    az_identifiable = [
        row
        for row in good_for_consensus
        if not row[
            "azimuth_ambiguous"
        ]
    ]

    az_consensus = Counter(
        (
            int(
                row[
                    "best_az_direction"
                ]
            ),
            int(
                row[
                    "best_az_offset_deg"
                ]
            ),
        )
        for row in az_identifiable
    )

    elapsed = (
        time.time()
        -
        start_all
    )

    text = [
        "=" * 80,
        "CORPUS VALIDATION SUMMARY",
        "=" * 80,
        f"Parser                    : {args.parser}",
        f"Viewer root               : {args.viewer_root}",
        f"CF2 dir                   : {args.cf2_dir}",
        f"Selected viewer models    : {len(model_names)}",
        f"Matched                   : {len(jobs)}",
        f"Completed comparisons     : {len(summary_rows)}",
        f"Errors                    : {len(errors)}",
        f"Declared-only mode        : {args.declared_only}",
        f"Elapsed                   : {elapsed:.2f} s",
        "",
        "QUALITY COUNTS",
    ]

    for key in sorted(
        qualities
    ):
        text.append(
            f"  {key:12s}: "
            f"{qualities[key]}"
        )

    text += [
        "",
        (
            "CONSENSUS INPUT "
            f"(MAE <= {args.consensus_max_mae:g} dB, "
            f"median <= {args.consensus_max_median:g} dB, "
            f"P90 <= {args.consensus_max_p90:g} dB)"
        ),
        f"  Models: {len(good_for_consensus)}",
        "",
        "Frequency shift counts:",
    ]

    for key, count in sorted(
        freq_consensus.items()
    ):
        text.append(
            f"  {key:+d}: {count}"
        )

    text.append(
        ""
    )
    text.append(
        "Arc mapping counts:"
    )

    for key, count in sorted(
        arc_consensus.items()
    ):
        text.append(
            f"  {key}: {count}"
        )

    text += [
        "",
        (
            "Azimuth mapping counts "
            "(only non-ambiguous models):"
        ),
        f"  Identifiable models: {len(az_identifiable)}",
    ]

    for (
        direction,
        offset_deg,
    ), count in az_consensus.most_common():
        sign = (
            "+x"
            if direction == 1
            else "-x"
        )

        text.append(
            f"  {sign} + {offset_deg:3d} deg: "
            f"{count}"
        )

    text += [
        "",
        "Interpretation rule:",
        "  A systematic transformation between Viewer and parser is evidence",
        "  of a convention difference, not by itself proof that the CF2 binary",
        "  parser is structurally wrong. Keep parser V5 frozen until the corpus",
        "  separates Viewer-display conventions from binary-layout errors.",
        "",
        "Outputs:",
        f"  {args.output_dir / 'match_manifest.csv'}",
        f"  {args.output_dir / 'corpus_summary.csv'}",
        f"  {args.output_dir / 'corpus_hypotheses_top.csv'}",
        f"  {args.output_dir / 'errors.csv'}",
    ]

    summary_path = (
        args.output_dir
        /
        "corpus_summary.txt"
    )

    summary_path.write_text(
        "\n".join(
            text
        )
        +
        "\n",
        encoding="utf-8",
    )

    print()
    print(
        "\n".join(
            text
        )
    )


if __name__ == "__main__":
    main()
