services:
  pra-benchmark:
    build: .
    environment:
      PRA_NUM_THREADS: "1"
      OMP_NUM_THREADS: "1"
      OPENBLAS_NUM_THREADS: "1"
      MKL_NUM_THREADS: "1"
    volumes:
      - ./results:/app/results
